### ISSUE TITLE
CMakeLists.txt can not be found during build on openSUSE with the latest release

### ISSUE THREAD

**Issue by skriesch** [qorelanguage/module-openldap#38]
I want to introduce qore-module-ldap at openSUSE again.
Firstly, I have used the latest spec file from this Github repository as a foundation. CMakeLists.txt can not be found:

```
[   24s] + cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_SKIP_RPATH=1 -DCMAKE_SKIP_INSTALL_RPATH=1 -DCMAKE_SKIP_BUILD_RPATH=1 -DCMAKE_PREFIX_PATH=/lib64/cmake/Qore .
[   24s] CMake Warning:
[   24s]   Ignoring extra path from command line:
[   24s] 
[   24s]    "."
[   24s] 
[   24s] 
[   24s] CMake Error: The source directory "/home/abuild/rpmbuild/BUILD/qore-openldap-module-1.2" does not appear to contain CMakeLists.txt.
```

Then I tried it with the spec file inside of the 1.2 release. It is working.
The difference is the following:
```
+./configure RPM_OPT_FLAGS="$RPM_OPT_FLAGS" --prefix=/usr --disable-debug 
%build
-export CXXFLAGS="%{?optflags}"
-cmake -DCMAKE_INSTALL_PREFIX=%{_prefix} -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_SKIP_RPATH=1 -DCMAKE_SKIP_INSTALL_RPATH=1 -DCMAKE_SKIP_BUILD_RPATH=1 -DCMAKE_PREFIX_PATH=${_prefix}/lib64/cmake/Qore .
-make %{?_smp_mflags}
+%{__make}
 
%install
-make DESTDIR=%{buildroot} install %{?_smp_mflags}
+rm -rf $RPM_BUILD_ROOT
+mkdir -p $RPM_BUILD_ROOT/%{module_dir}
+mkdir -p $RPM_BUILD_ROOT/usr/share/doc/qore-openldap-module
+make install DESTDIR=$RPM_BUILD_ROOT
```

What was the reason for the change for Fedora? Default it should work on both.

**Comment by davidnich** [comment]
@skriesch it was to use cmake - almost everything has been migrated to cmake, and I believe there was some issue with the RPM autotools builds.

it is also being built here for opensuse: https://build.opensuse.org/package/show/home:davidnichols/qore-openldap-module - for Factory, Leap 15.2, and Tumbleweed

where did you get the package without the CMakeLists.txt file BTW?  I suppose that would be the source of the problem.

**Comment by skriesch** [comment]
I have reproduced it in my home repository again:
https://build.opensuse.org/package/show/home:AdaLovelace:branches:devel:languages:misc/qore-openldap-module

The differences between the upstream development spec file and my used spec file are:
- version number 1.2 instead of 1.2.2
- Source URL from Github

I have used the release download possibility here on Github:
https://github.com/qorelanguage/module-openldap/releases

**Comment by skriesch** [comment]
Can you release the version 1.2.2 perhaps also on Github, please? Then I can test it against that.

**Comment by davidnich** [comment]
@skriesch published - let me know if you find any issues

**Comment by skriesch** [comment]
It is building with this tar archive. So the version 1.2.2 was required. Then there was any configuration dependency between these 2 versions.
Thanks!

**Comment by davidnich** [comment]
glad its working, thanks for your attention to this issue
